disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - modifier_order
  - overridden_super_call
  - prohibited_interface_builder
  - redundant_nil_coalescing
  - strict_fileprivate
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

excluded:
  - .build
  - build
  - Pods
  - vendor

line_length:
  warning: 200
  error: 300
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 700
  error: 1000

file_length:
  warning: 1200
  error: 1500

cyclomatic_complexity:
  warning: 25
  error: 40

function_parameter_count:
  warning: 8
  error: 12

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3
